theme: minima
title: ICSE 9th Biology
description: Comprehensive study materials for ICSE 9th grade Biology

# Build settings
markdown: kramdown

# Navigation
header_pages:
	- index.md
	- 08-Five Kingdom Classification/README.md

# Collections
collections:
	chapters:
		output: true
		permalink: /:collection/:name/
