theme: minima
title: ICSE 9th Biology - Study Notes
description: Comprehensive study materials for ICSE 9th grade Biology

# Build settings
markdown: kramdown

# Navigation
header_pages:
  - index.md
  - 02-cell-the-unit-of-life/README.md
  - 06-Seeds-Structure-and-Germination/README.md
  - 08-Five-Kingdom-Classification/README.md

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:name/

# Force rebuild timestamp
updated: 2025-09-13
